### ISSUE TITLE
Bill to add text to ID Req doc on identifying 3rd party issuer

### ISSUE THREAD

**Issue by gitnnelg** [w3c/tv-ggie#3]
IDs are issued to be unique within the scope of the domain managed by a third party.  Require mechanism to identify the domain an issued ID originate from so as to distinguish it.

**Comment by gitwjr** [comment]
Done. See ID Requirements; **Issuer Requirement** #3. #

**Comment by gitwjr** [comment]
Done. See ID Requirements, Issuer Requirements #3. Closed.
