### ISSUE TITLE
Kaz to review git ggie members to ensure team had full access

### ISSUE THREAD

**Issue by gitnnelg** [w3c/tv-ggie#4]
Team member are not showing up in the assignee list to assign issues to.

**Comment by ashimura** [comment]
I invited Bill, Leslie and Julian.
Bill and Leslie have joined the tv-ggie Team, and am waiting for Julian's response.
If there are other GGIE participants who want to join, please let me know.

**Comment by sitkevij** [comment]
I've successfully joined, thanks for the invite.

**Comment by ashimura** [comment]
good! welcome aboard, Julian!
